### ISSUE TITLE
will it be possible for me to add this pdf to text plugin to my angular 2 project (ionic 2)

### ISSUE THREAD

**Issue by jose2007kj** [schwamster/pdf_to_text#1]
sir, if possible ...........how to add?............ thanks

**Comment by schwamster** [comment]
pdf_to_text is not a plugin. It is a **service** you can use to turn pdf to text. You can however just check out the npm package "pdf-to-text" that is used under the hood and integrate that in your application: https://www.npmjs.com/package/pdf-to-text 
see also the git project: https://github.com/zetahernandez/pdf-to-text

**Comment by jose2007kj** [comment]
thank you sir........i will check that
